- name: Create Instance
  ec2:
    key_name: "{{ ec2_key }}"
    instance_type: "m4.large"
    group: ocp4-extender
    image: "ami-c86c3f23"
    count: 1
    region: "{{ ec2_region }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}" # todo get from OCP4
    assign_public_ip: yes
    instance_tags:
      creator: ocp4-extender
      creator_arn: "{{ caller_facts.arn }}"
      user: "{{ ec2_user }}"
      Name: "{{ ec2_user }}-ocp4-extender"
    wait: yes
  register: ec2_instance
