- name: Get AWS account information
  aws_caller_facts:
  register: caller_facts

- ec2_instance_facts:
    filters:
      "tag:Name": "{{ ansible_user }}-nfs-server"
      "tag:creator_arn": "{{ caller_facts.arn }}"
    region: "{{ ec2_region }}"
  register: ec2_metadata

- set_fact:
    instances: "{{ ec2_metadata.instances | map(attribute='instance_id') | list }}"

- debug:
    msg:
    - "These instances will be terminated"
    - "{{ instances }}"

- local_action:
    module: ec2
    instance_ids: "{{ instances }}"
    state: absent
    region: "{{ ec2_region }}"
