- ec2_instance_facts:
    filters:
      "tag:Name": "{{ ansible_user }}-origin3-dev"
      "tag:creator_arn": "{{ caller_facts.arn }}"
    region: "{{ ec2_region }}"
  register: ec2_metadata
  tags: ocp3-origin

# - name: Extract tag from metadata
#   set_fact:
#     ocp4_tag: "{{ lookup('file', ) }}"

- ec2_instance_facts:
    filters:
      "tag:Name": "{{ ansible_user }}-origin3-dev"
      "tag:creator_arn": "{{ caller_facts.arn }}"
    region: "{{ ec2_region }}"
  register: ec2_metadata
  tags: ocp4
  
- debug:
    var: ec2_metadata

- name: Extract info about source cluster subnet
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ ec2_metadata.instances[0].vpc_id }}"
  register: subnet_inst

- name: Extract info about source cluster igw
  ec2_vpc_igw_facts:
    region: "{{ ec2_region }}"
    filters:
      "tag:Name": "origin3-dev"
  register: source_igw

- debug:
   var: subnet_inst

- debug:
    var: source_igw


- set_fact:
    source_vpc: "{{ ec2_metadata.instances[0].vpc_id }}"
    source_subnet: "{{ ec2_metadata.instances[0].subnet_id }}"
    source_cidr: "{{ subnet_inst.subnets[0].cidr_block }}"
    source_igw: "{{ source_igw.internet_gateways[0].internet_gateway_id }}"

- name: Extract route table id for NFS VPC
  ec2_vpc_route_table_facts:
      region: "{{ ec2_region }}"
      filters:
        vpc-id: "{{ ec2_vpc.vpc.id }}"
  register: vpc_routes

- set_fact:
    route_id: "{{ item.associations | selectattr('subnet_id', 'equalto', ec2_subnet.subnet.id ) | list }}"
  loop: "{{ vpc_routes.route_tables | selectattr('associations') | list }}"

- set_fact:
    nfs_route_id: "{{ route_id[0]['route_table_id'] }}"

- name: Extract route table id for source cluster VPC
  ec2_vpc_route_table_facts:
      region: "{{ ec2_region }}"
      filters:
        vpc-id: "{{ source_vpc }}"
  register: vpc_routes

- set_fact:
    route_id: "{{ item.associations | selectattr('subnet_id', 'equalto', source_subnet ) | list }}"
  loop: "{{ vpc_routes.route_tables | selectattr('associations') | list }}"

- set_fact:
    source_route_id: "{{ route_id[0]['route_table_id'] }}"

- debug:
    var: nfs_route_id

- debug:
    var: source_route_id

- debug:
    var: source_vpc

- debug:
    var: source_subnet

- debug:
    var: source_cidr

- debug:
    var: source_igw
